const ComingSoonBadgeJson = [
  {
    activityId:"5566",
    activityName: "Activity name is displayed here",
    activityDescription: "Here is the activity details",
    activityIssuer: "Alex",
    activityStatus: "01",
    activityLink: "...",
    startDateTime: "...",
    endDateTime: "...",
    timeZone:"",
    activityAccess:"Telegram: htttp://www.t.me.wei",
    organizer:"...",
    initiatorRole: "...",
    twitter:"",
    mail:"",
    discord: "",
    telegram:"",
    reddit:"",
    badgeAsaId: "1",
    badgeImgUrl: "https://drive.google.com/file/d/1oTqH1Xq5d_xVnRt8EbFLpUw2qSe3YjzV/view",
    badgeName: "badge1",
    badgeTotal: 100,
    badgeHasClaimed: 30,
    countdown: "1Y 0M",
  },
  {
    activityId:"2",
    activityName: "BBB",
    activityDescription: "...",
    activityIssuer: "Ben",
    activityStatus: "01",
    activityLink: "...",
    startDateTime: "...",
    endDateTime: "...",
    timeZone:"",
    activityAccess:"...",
    organizer:"...",
    initiatorRole: "...",
    twitter:"",
    mail:"",
    discord: "",
    telegram:"",
    reddit:"",
    badgeAsaId: "2",
    badgeImgUrl: "/img/badge_image.png",
    badgeName: "badge2",
    badgeTotal: 100,
    badgeHasClaimed: 78,
    countdown: "1Y 1M",
  },
  {
    activityId:"1",
    activityName: "CCC",
    activityDescription: "...",
    activityIssuer: "Carl",
    activityStatus: "01",
    activityLink: "...",
    startDateTime: "...",
    endDateTime: "...",
    timeZone:"",
    activityAccess:"...",
    organizer:"...",
    initiatorRole: "...",
    twitter:"",
    mail:"",
    discord: "",
    telegram:"",
    reddit:"",
    badgeAsaId: "3",
    badgeImgUrl: "/img/badge_image.png",
    badgeName: "badge3",
    badgeTotal: 100,
    badgeHasClaimed: 22,
    countdown: "2Y 8M",

  },
  {
    activityId:"1",
    activityName: "DDD",
    activityDescription: "...",
    activityIssuer: "Dave",
    activityStatus: "04",
    activityLink: "...",
    startDateTime: "...",
    endDateTime: "...",
    timeZone:"",
    activityAccess:"...",
    organizer:"...",
    initiatorRole: "...",
    twitter:"",
    mail:"",
    discord: "",
    telegram:"",
    reddit:"",
    badgeAsaId: "4",
    badgeImgUrl: "/img/badge_image.png",
    badgeName: "badge4",
    badgeTotal: 100,
    badgeHasClaimed: 41,
    countdown: "1Y 9M",
  }
  ]
    
    export default ComingSoonBadgeJson;
  